### ISSUE TITLE
Python 3.7 reserved keyword "async" conflicting with the pip version of the lib

### ISSUE THREAD

**Issue by lucascharlesz** [closeio/closeio-api#100]
Guys, I would have made a pull request, but it seems that you didn't updated the repository with the latest version of the API published at Pip.

So, you must change the name of the variable due to it had become a reserved keyword in you __init__ file:
def __init__(self, base_url, api_key, tz_offset=None, `async`=False, max_retries=5):

**Comment by philfreo** [comment]
See https://github.com/closeio/closeio-api/issues/85 which is where we are tracking Python 3 support.
