### ISSUE TITLE
If lead has no name, merge_leads.py throws an error

### ISSUE THREAD

**Issue by cdmckay** [closeio/closeio-api#14]
When trying to run the merge_leads.py script, I get this error:

```
Traceback (most recent call last):
  File "./merge_leads.py", line 47, in <module>
    is_duplicate = last_lead and lead['name'].strip() and last_lead['name'].strip().lower() == lead['name'].strip().lower()
AttributeError: 'NoneType' object has no attribute 'strip'
```

I believe this is because if lead doesn't have a name, it returns None.

**Comment by cdmckay** [comment]
I also found that if I replace lined 47 with:

```
is_duplicate = last_lead and lead['name'] and lead['name'].strip() and last_lead['name'] and last_lead['name'].strip().lower() == lead['name'].strip().lower()
```

It fixes it.

**Comment by philfreo** [comment]
Closing since scripts have moved into https://github.com/closeio/closeio-api-scripts. @eengoron please reopen an issue there if you think this is still an issue.
