### ISSUE TITLE
Migrate to Requests-Futures

### ISSUE THREAD

**Issue by anemitz** [closeio/closeio-api#28]
https://github.com/ross/requests-futures

It's the future: https://github.com/kennethreitz/grequests/pull/22

Also handles errors much better: https://github.com/elasticsales/closeio-api/issues/7

**Comment by wojcikstefan** [comment]
We decided to let the user choose whatever async strategy they want to pursue on top of our synchronous client (see https://github.com/closeio/closeio-api/pull/78#issuecomment-276209971).
