### ISSUE TITLE
bulk_update_leads_info script doesn't describe how to update custom fields

### ISSUE THREAD

**Issue by anemitz** [closeio/closeio-api#38]

**Comment by anemitz** [comment]
@congocongo

**Comment by philippe2803** [comment]
I'm wondering the same thing. I spent some time yesterday trying to update a custom field, and it did not work.
From the website, it says: 
> To update a single custom field without removing the others, use custom.field_name: updated_value instead of custom: { all: 'fields', listed: 'here' }. 

So I tried this:
```python
update_lead = api.put(lead_id, data={ "custom": {"field to update": "value to update"}})
```
The value changes, but as expected every other custom fields were deleted. So I tried the following (I believe this is what is implied by the comment from their site):
```python
update_lead = api.put(lead_id, data={"field to update": "value to update"})
```
I do not receive any error message, and it looks like it works, however when I check my lead on close.io, the value has not changed at all. 

The only way around I found is to pull every custom fields of the lead I want to update beforehand, and then push everything onto the lead back again, including the updated value. I'm annoyed by this solution though, as I'm not taking advantage of the patch behavior that Close.io has. Everything works well on any other fields, I'm just stucked with the custom fields.

Am I being wrong somewhere and/or has anyone else faced the same issue?

**Comment by wojcikstefan** [comment]
@philippe2803 try `update_lead = api.put(lead_id, data={"custom.field to update": "value to update"})`

**Comment by philippe2803** [comment]
@wojcikstefan That worked! Thank you so much.

**Comment by philfreo** [comment]
Closing since scripts have moved into https://github.com/closeio/closeio-api-scripts. You or @eengoron can open an issue there if you think should still be handled.
