### ISSUE TITLE
Script to transfer leads (and nested contacts, notes, calls, etc.) from one organization to another

### ISSUE THREAD

**Issue by anemitz** [closeio/closeio-api#40]
Should take a search query as input and 2 API keys (from different orgs)

Transfer all the leads matching the search query

As well as all the nested objects on the leads (Contacts, Tasks, Opportunities), and the Calls & Note Activities

Emails don't need to transfer since we'll sync them ourselves but all other lead data should transfer over.

If lead statuses or opportunity statuses don't exist it should clearly print out that you need to set up those statuses within the destination organization first.

**Comment by anemitz** [comment]
@congocongo

**Comment by congocongo** [comment]
yes, accepted

**Comment by philfreo** [comment]
@congocongo reminder about this one

**Comment by anemitz** [comment]
@congocongo any update here?

**Comment by philfreo** [comment]
Closing since scripts have moved into https://github.com/closeio/closeio-api-scripts. @anemitz  please reopen an issue there if you still want this.
