### ISSUE TITLE
bulk_update_lead_info for adding a contact doesn't appear to work

### ISSUE THREAD

**Issue by anemitz** [closeio/closeio-api#42]
```
(closeio)--- Projects/closeio-api ‹master» python scripts/bulk_update_leads_info.py ~/Downloads/test.csv --api-key <redacted> --confirmed
[2015-05-15 18:59:23,018] INFO Starting new HTTPS connection (1): app.close.io
[2015-05-15 18:59:23,539] INFO line 2 updated: lead_iyTYlkzfVWKn0rH0x1yGrPX2vMOzzCsOdBK205WrzLk Plumbing Medic
[2015-05-15 18:59:23,539] INFO summary: updated[1], new[0], skipped[0]
(closeio)--- Projects/closeio-api ‹master» cat ~/Downloads/test.csv
lead_id,contact_name,contact_phone,,,,,,
lead_iyTYlkzfVWKn0rH0x1yGrPX2vMOzzCsOdBK205WrzLk,Conference Call Line,+1818-452-3980,,,,,,
```

No contact added to https://app.close.io/lead/lead_iyTYlkzfVWKn0rH0x1yGrPX2vMOzzCsOdBK205WrzLk/

**Comment by anemitz** [comment]
If there was no contact added why was there no error?  How can I make this just add a contact to this lead?

**Comment by anemitz** [comment]
https://help.close.io/agent/case/25982

**Comment by philfreo** [comment]
@congocongo can you address @anemitz comments above?

**Comment by congocongo** [comment]
@anemitz can you run again with debug level?

**Comment by congocongo** [comment]
@anemitz  try with:

lead_id,contact1_name,contact1_phone,,,,,,
lead_iyTYlkzfVWKn0rH0x1yGrPX2vMOzzCsOdBK205WrzLk,Conference Call Line,+1818-452-3980,,,,,,

instead contact_name,contact_phone

**Comment by congocongo** [comment]
@philfreo can you close it? this is not a bug even.

**Comment by philfreo** [comment]
If the script's output/instructions isn't clear enough that @anemitz can't figure out how to use it, then the script needs to be better.

**Comment by philfreo** [comment]
e.g. if the issue is that invalid column names were supplied, then the script should tell you that clearly in an error message with instructions on what the valid column names are

**Comment by congocongo** [comment]
yes, good idea, will do it

**Comment by philfreo** [comment]
Closing since scripts have moved into https://github.com/closeio/closeio-api-scripts. You or @eengoron can open an issue there if you think should still be handled.
