### ISSUE TITLE
script to update the assigned user of an opportunity based on a csv

### ISSUE THREAD

**Issue by anemitz** [closeio/closeio-api#44]

**Comment by philfreo** [comment]
More details about what's in the csv and overall use case?

On Thursday, May 28, 2015, Anthony Nemitz <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsales/closeio-api/issues/44>.
>


-- 
Phil Freo
Product/Engineering @ Close.io <http://close.io/>
@philfreo <https://twitter.com/philfreo> | philfreo.com

**Comment by philfreo** [comment]
Scripts have moved into https://github.com/closeio/closeio-api-scripts
