### ISSUE TITLE
bulk_update_lead_info doesn't support addition of new addresses

### ISSUE THREAD

**Issue by anemitz** [closeio/closeio-api#49]

**Comment by philfreo** [comment]
Quick glance at the code/fields and it seem to support this. Can you give more details?

**Comment by anemitz** [comment]
https://github.com/closeio/closeio-api/blob/master/scripts/bulk_update_leads_info.py#L160

only supports updates to existing addresses.

**Comment by wojcikstefan** [comment]
There was actually a bug where instead of extracting `X` from `addressX_*`, the script would extract `s` for every address, essentially excluding any address column. I fixed it in da540d3.
