### ISSUE TITLE
user_reassign script skips over objects

### ISSUE THREAD

**Issue by thomasst** [closeio/closeio-api#59]
The user_reassign script doesn't update all the objects. It paginates through objects that match certain criteria (i.e. the old user), reassigns them to the new user, and then increases the `offset` to fetch the next batch. The problem is that when we reassign old objects, the results don't contain them anymore, and we end up skipping objects. We instead need to keep the `offset` at 0 and loop until no more objects are left (_except_ for in the dry run).

**Comment by thomasst** [comment]
Also, since these views are powered by Elasticsearch it's possible that updates take a second to propagate (i.e. it may take a second until updated leads are excluded in a request).

* We could keep an array of lead IDs that were reassigned and make sure we don't process them multiple times
* We could sleep between GET requests and make sure they are at least a second apart.

In all cases, we should keep looping until the GET endpoint returns no more objects and keep the offset at 0.

**Comment by thomasst** [comment]
@flevour Hey Francesco, would you be willing to fix this issue? Please let me know. Also happy to answer any questions you may have.

**Comment by flevour** [comment]
@thomasst I can look into this, I've worked on a similar issue in the past. Let me know if you have a desired timeframe or anytime soon is good for you!

**Comment by thomasst** [comment]
It's an annoying issue for the support team, so the sooner the better :) Thanks!

**Comment by philfreo** [comment]
Closing since scripts have moved into https://github.com/closeio/closeio-api-scripts. @eengoron please reopen an issue there if you think this is still an issue.
