### ISSUE TITLE
Move scripts to a separate repo

### ISSUE THREAD

**Issue by philfreo** [closeio/closeio-api#64]
Let's have this repo just be our Python API client and move example scripts to their own repo called closeio-api-scripts

**Comment by philfreo** [comment]
Once we do this, I suggest we rename this repo to `closeio-python` (the package can stay as `closeio`)

**Comment by philfreo** [comment]
I've created https://github.com/closeio/closeio-api-scripts that we should move all the scripts to. @eengoron is this something you'd like to handle?

**Comment by eengoron** [comment]
I can do that. Just for clarification though (to make sure I don't make any
mistakes), which files am I moving? Just the scripts folder? Essentially,
that would make this repo contain close_api, requirements.txt, and setup.py.

Let me know!

**Comment by philfreo** [comment]
Exactly. What should be moved is everything in `scripts/` (plus some parts of the README)

**Comment by anemitz** [comment]
and the new repo should have a requirements.txt with the closeio package.

**Comment by philfreo** [comment]
@eengoron looking forward to that PR

**Comment by philfreo** [comment]
Done, thanks!
https://github.com/closeio/closeio-api-scripts
