### ISSUE TITLE
Async request error handling

### ISSUE THREAD

**Issue by pirate** [closeio/closeio-api#7]
Hey close.io devs, this is Nick Sweeting with drchrono, thanks for writing this python library, it makes our lives a lot easier.

I'm writing a PR for the TODO you guys put in __init__.py:71  
[grequests now supports passing an exception_handler](https://github.com/kennethreitz/grequests/pull/15) function so we no longer have to deal with this APIError() monkey business.  I've started updating the code and should have a pull request ready in a few days.

the new code will follow this pattern:

``` python
def map(self, reqs, max_retries=None):
    import grequests
    max_retries = max_retries or self.max_retries

    retries = 0
    failed = []
    responses = grequests.map(reqs, exception_handler=lambda req, excp: failed.append(req))

    while failed and retries < self.max_retries:
        succeeded = grequests.map(failed, exception_handler=lambda req, excp: pass)       # leave the ones that continue failing in failed
        failed = [ req for req in failed if req not in reversed(succeeded) ]              # checking if reversed succeeded contains our request is faster because we append good ones to the end
        responses += succeeded
        retries += 1
        time.sleep(2)

    return [resp.json() for resp in responses]
```

**Comment by anemitz** [comment]
Hey Nick,
That PR was closed in lieu of https://github.com/kennethreitz/grequests/pull/22 which looks like it's stagnant.  The discuss seems lead us to instead using https://github.com/ross/requests-futures which supports error handling.

**Comment by wojcikstefan** [comment]
Hi Nick, we decided to move away from `grequests` in v1.0 (you can see some arguments for it in https://github.com/closeio/closeio-api/pull/78#issuecomment-275871159 and in https://github.com/closeio/closeio-api/pull/78#issuecomment-276209971).

To replicate a similar behavior, you can spawn multiple `api.get/post/put/delete` requests in a `gevent.pool`.
