### ISSUE TITLE
Unify closeio/closeio_api on PyPi

### ISSUE THREAD

**Issue by thomasst** [closeio/closeio-api#72]
Currently, `pip install closeio` install version 0.3 of the API client, and `pip install closeio_api` installs version 0.1 of the API client. `setup.py` claims the latest version is 0.4, and the latest version in master is different, too. We should unify this, and also update the README.

**Comment by zevaverbach** [comment]
This would have saved me 45 mins of trouble today!

**Comment by wojcikstefan** [comment]
`pip install closeio` installs the correct version now (`closeio==0.4`). I also hid the old `closeio_api`  release so that https://pypi.python.org/pypi/closeio_api returns a 404.

Sorry you ran into this issue @zevaverbach!
