### ISSUE TITLE
add_argument --confirmed should be added to wiki page.

### ISSUE THREAD

**Issue by kinnth** [closeio/closeio-api#74]
Have been using this and I ended up getting very confused by the fact that it wasn't actually editing my data till I added this argument.

I suggest within the wiki that you should mention this step to actually perform the action to merge the contacts.  I assumed that during the print out the action was being taken when actually it was just displaying without taking the action.

**Comment by philfreo** [comment]
Good suggestion. We've since moved the scripts out of this repo and into https://github.com/closeio/closeio-api-scripts - but perhaps @eengoron can document it better there.
